# Error Handling in JavaScript

## Throw, and Try...Catch...Finally

The `try` statement allows you to define a block of code to be tested for errors while it is being executed..

The `catch` statement allows you to define a block of code to be executed, if an error occurs in the try block.

```
try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
}
```

The `finally` statement defines a code block to run regardless of the result.

The `throw` statement defines a custom error.
